'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const SAVE_KEY='cookie_clicker_fixed_v1';
const BUILDINGS=[
{id:'cursor',name:'Curseur',icon:'🖱️',baseCost:15,baseCps:.1,desc:'Clique automatiquement.'},{id:'grandma',name:'Grand-mère',icon:'👵',baseCost:100,baseCps:1,desc:'Cuit des cookies avec amour.'},{id:'farm',name:'Ferme',icon:'🌾',baseCost:1100,baseCps:8,desc:'Cultive des cookies.'},{id:'mine',name:'Mine',icon:'⛏️',baseCost:12000,baseCps:47,desc:'Extrait des pépites de cookie.'},{id:'factory',name:'Usine',icon:'🏭',baseCost:130000,baseCps:260,desc:'Produit en masse.'},{id:'bank',name:'Banque',icon:'🏦',baseCost:1400000,baseCps:1400,desc:'Investit dans les cookies.'},{id:'temple',name:'Temple',icon:'🛕',baseCost:20000000,baseCps:7800,desc:'Bénédiction sucrée.'},{id:'wizard',name:'Tour de sorcier',icon:'🧙',baseCost:330000000,baseCps:44000,desc:'Magie biscuitée.'},{id:'shipment',name:'Expédition',icon:'🚀',baseCost:5100000000,baseCps:260000,desc:'Cookies depuis l’espace.'},{id:'lab',name:'Laboratoire',icon:'🧪',baseCost:75000000000,baseCps:1600000,desc:'Science du cookie.'}
];
const UPGRADES=[
{id:'click_1',icon:'🖱️',name:'Meilleure souris',cost:100,desc:'+1 par clic',unlock:g=>g.totalClicks>=10,effect:g=>g.cpc+=1},
{id:'click_2',icon:'🖱️✨',name:'Souris renforcée',cost:750,desc:'+2 par clic',unlock:g=>g.totalClicks>=50,effect:g=>g.cpc+=2},
{id:'click_3',icon:'⚡',name:'Double clic',cost:5000,desc:'Clics x2',unlock:g=>g.totalClicks>=100,effect:g=>g.cpc*=2},
{id:'click_4',icon:'🍪',name:'Doigts chocolatés',cost:25000,desc:'+10 par clic',unlock:g=>g.totalClicks>=250,effect:g=>g.cpc+=10},
{id:'grandma_1',icon:'👓',name:'Lunettes de mamie',cost:1000,desc:'Grand-mères x2',unlock:g=>g.buildings.grandma.count>=1,effect:g=>g.buildings.grandma.mult*=2},
{id:'grandma_2',icon:'😈',name:'Mamies énervées',cost:15000,desc:'Grand-mères x3',unlock:g=>g.buildings.grandma.count>=10,effect:g=>g.buildings.grandma.mult*=3},
{id:'farm_1',icon:'🌱',name:'Engrais',cost:12000,desc:'Fermes x2',unlock:g=>g.buildings.farm.count>=3,effect:g=>g.buildings.farm.mult*=2},
{id:'mine_1',icon:'💣',name:'Dynamite sucrée',cost:200000,desc:'Mines x2',unlock:g=>g.buildings.mine.count>=3,effect:g=>g.buildings.mine.mult*=2},
{id:'factory_1',icon:'🔧',name:'Chaîne optimisée',cost:1500000,desc:'Usines x2',unlock:g=>g.buildings.factory.count>=3,effect:g=>g.buildings.factory.mult*=2},
{id:'luxury',icon:'💎',name:'Biscuits de luxe',cost:5000000,desc:'Clics x5',unlock:g=>g.totalBaked>=1000000,effect:g=>g.cpc*=5}
];
const ACH=[{id:'a1',icon:'🍪',name:'Premier cookie',desc:'Cuire 1 cookie',done:g=>g.totalBaked>=1},{id:'a2',icon:'💯',name:'Centenaire',desc:'Cuire 100 cookies',done:g=>g.totalBaked>=100},{id:'a3',icon:'🖱️',name:'Cliqueur',desc:'Faire 100 clics',done:g=>g.totalClicks>=100},{id:'a4',icon:'🏭',name:'Industriel',desc:'Avoir 1 usine',done:g=>g.buildings.factory.count>=1},{id:'a5',icon:'💰',name:'Millionnaire',desc:'Cuire 1 million',done:g=>g.totalBaked>=1e6},{id:'a6',icon:'👑',name:'Baron du cookie',desc:'Cuire 1 milliard',done:g=>g.totalBaked>=1e9}];
const NEWS=['Bienvenue dans Cookie Clicker.','La bourse du biscuit explose.','Des grand-mères protestent contre la pénurie de lait.','Un cookie géant aperçu au-dessus de Los Santos.','Des usines tournent jour et nuit.'];
const fresh=()=>({cookies:0,totalBaked:0,totalClicks:0,cpc:1,cps:0,playTime:0,lastSave:Date.now(),buyMode:'1',clickVolume:.35,buildings:Object.fromEntries(BUILDINGS.map(b=>[b.id,{count:0,mult:1}])),upgrades:{},achievements:{},lastFrame:0,lastUi:0,dirtyShop:true,dirtyAch:true});
let game=fresh(), audioCtx=null;
function ctx(){audioCtx??=new(window.AudioContext||window.webkitAudioContext)();return audioCtx}
function beep(freq=800,dur=.035,vol=.18){try{const c=ctx(),o=c.createOscillator(),g=c.createGain(),f=c.createBiquadFilter();o.type='square';o.frequency.setValueAtTime(freq,c.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.55,c.currentTime+dur);f.type='highpass';f.frequency.value=420;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(vol*game.clickVolume,c.currentTime+.003);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+dur);o.connect(f);f.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+dur+.01)}catch(e){}}
function fmt(n){if(!isFinite(n))return'∞';if(n<1000)return Math.floor(n).toString();const u=['','k','M','B','T','Qa','Qi','Sx','Sp'];let i=0;while(n>=1000&&i<u.length-1){n/=1000;i++}return n.toFixed(2)+' '+u[i]}
function time(s){s=Math.floor(s);let h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return h?`${h}h ${m}m`:m?`${m}m ${sec}s`:`${sec}s`}
function bCost(b,count=game.buildings[b.id].count){return Math.ceil(b.baseCost*Math.pow(1.15,count))}
function costFor(b,n){let t=0,c=game.buildings[b.id].count;for(let i=0;i<n;i++)t+=bCost(b,c+i);return t}
function maxAffordable(b){let n=0,t=0,c=game.buildings[b.id].count;while(n<10000){let next=bCost(b,c+n);if(t+next>game.cookies)break;t+=next;n++}return{n,total:t}}
function recalc(){game.cps=BUILDINGS.reduce((s,b)=>s+game.buildings[b.id].count*b.baseCps*game.buildings[b.id].mult,0)}
function log(m){let d=document.createElement('div');d.textContent='• '+m;$('#log').prepend(d);while($('#log').children.length>40)$('#log').lastChild.remove()}
function toast(m){let t=document.createElement('div');t.className='toast';t.textContent=m;$('#toastLayer').appendChild(t);setTimeout(()=>t.remove(),2500)}
function floating(x,y,text){let f=document.createElement('div');f.className='floating';f.textContent=text;f.style.left=x+'px';f.style.top=y+'px';$('#floatLayer').appendChild(f);setTimeout(()=>f.remove(),900)}
function clickCookie(e){game.cookies+=game.cpc;game.totalBaked+=game.cpc;game.totalClicks++;game.dirtyShop=true;beep(950,.045,.2);floating(e.clientX-8,e.clientY-18,'+'+fmt(game.cpc));checkAch();updateUI()}
function buyBuilding(id){let b=BUILDINGS.find(x=>x.id===id);let qty=game.buyMode==='max'?maxAffordable(b).n:Number(game.buyMode);if(!qty)return;let price=game.buyMode==='max'?maxAffordable(b).total:costFor(b,qty);if(price>game.cookies)return;game.cookies-=price;game.buildings[id].count+=qty;recalc();game.dirtyShop=true;beep(300,.07,.22);log(`Acheté ${qty} x ${b.name}`);checkAch();updateUI()}
function buyUpgrade(id){let u=UPGRADES.find(x=>x.id===id);if(!u||game.upgrades[id]||!u.unlock(game)||game.cookies<u.cost)return;game.cookies-=u.cost;game.upgrades[id]=true;u.effect(game);recalc();game.dirtyShop=true;beep(1200,.08,.25);toast('⭐ '+u.name);log('Amélioration : '+u.name);updateUI()}
function checkAch(){let ch=false;for(let a of ACH){if(!game.achievements[a.id]&&a.done(game)){game.achievements[a.id]=true;ch=true;toast('🏆 '+a.name);log('Succès débloqué : '+a.name)}}if(ch)game.dirtyAch=true}
function renderShop(){let shop=$('#shop');shop.innerHTML='';for(let b of BUILDINGS){let qty=game.buyMode==='max'?maxAffordable(b).n:Number(game.buyMode),cost=game.buyMode==='max'?maxAffordable(b).total:costFor(b,qty);let can=cost>0&&game.cookies>=cost;let div=document.createElement('div');div.className='building '+(can?'affordable':'disabled');div.onclick=()=>buyBuilding(b.id);div.innerHTML=`<div class="b-icon">${b.icon}</div><div><div class="b-name">${b.name}</div><div class="b-desc">${b.desc}</div><div class="b-cost">${fmt(cost||bCost(b))} 🍪 • ${fmt(b.baseCps*game.buildings[b.id].mult)}/s</div></div><div class="b-owned">${game.buildings[b.id].count}</div>`;shop.appendChild(div)}game.dirtyShop=false}
function renderUpgrades(){let box=$('#upgrades');box.innerHTML='';for(let u of UPGRADES){let unlocked=u.unlock(game),bought=!!game.upgrades[u.id],can=unlocked&&!bought&&game.cookies>=u.cost;let div=document.createElement('div');div.className='upgrade '+(bought?'bought':!unlocked?'locked':can?'affordable':'');div.dataset.tip=`${u.name}\n${u.desc}\n${fmt(u.cost)} cookies`;div.textContent=u.icon;div.onclick=()=>{if(unlocked&&!bought)buyUpgrade(u.id)};box.appendChild(div)}}
function renderAch(){let box=$('#achievements');box.innerHTML='';for(let a of ACH){let ok=!!game.achievements[a.id],d=document.createElement('div');d.className='achievement '+(ok?'':'locked');d.innerHTML=`<div class="title">${ok?'✅':'🔒'} ${a.icon} ${a.name}</div><div class="desc">${a.desc}</div>`;box.appendChild(d)}game.dirtyAch=false}
function updateUI(){$('#cookieCount').textContent=fmt(game.cookies);$('#cps').textContent=fmt(game.cps)+' / seconde';$('#cpc').textContent='+'+fmt(game.cpc)+' / clic';$('#totalBaked').textContent=fmt(game.totalBaked);$('#totalClicks').textContent=fmt(game.totalClicks);$('#playTime').textContent=time(game.playTime);$('#achCount').textContent=Object.values(game.achievements).filter(Boolean).length+'/'+ACH.length;renderUpgrades();if(game.dirtyShop)renderShop();if(game.dirtyAch)renderAch()}
function save(){game.lastSave=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(game));$('#saveStatus').textContent='💾 Sauvegardé';setTimeout(()=>$('#saveStatus').textContent='💾 Sauvegarde locale',1000)}
function load(){let raw=localStorage.getItem(SAVE_KEY);if(!raw)return;try{let data=JSON.parse(raw);game={...fresh(),...data};for(let b of BUILDINGS)game.buildings[b.id]??={count:0,mult:1};recalc();let off=Math.min(28800,Math.floor((Date.now()-(game.lastSave||Date.now()))/1000));if(off>10&&game.cps>0){let gain=off*game.cps;game.cookies+=gain;game.totalBaked+=gain;toast('⏱️ Hors ligne : +'+fmt(gain))}}catch(e){console.error(e);localStorage.removeItem(SAVE_KEY)}}
function exportSave(){navigator.clipboard.writeText(btoa(unescape(encodeURIComponent(JSON.stringify(game)))));toast('Sauvegarde copiée')}
function importSave(){let c=prompt('Colle ta sauvegarde :');if(!c)return;try{localStorage.setItem(SAVE_KEY,decodeURIComponent(escape(atob(c))));location.reload()}catch(e){toast('Sauvegarde invalide')}}
function reset(){if(confirm('Reset toute la progression ?')){localStorage.removeItem(SAVE_KEY);location.reload()}}
function loop(ts){if(!game.lastFrame)game.lastFrame=ts;let dt=Math.min(.2,(ts-game.lastFrame)/1000);game.lastFrame=ts;game.playTime+=dt;let gain=game.cps*dt;game.cookies+=gain;game.totalBaked+=gain;if(ts-game.lastUi>120){updateUI();game.lastUi=ts}requestAnimationFrame(loop)}
function init(){load();$('#cookieBtn').onclick=clickCookie;$('#volume').value=Math.round(game.clickVolume*100);$('#volume').oninput=e=>game.clickVolume=e.target.value/100;$$('.mode').forEach(b=>b.onclick=()=>{$$('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');game.buyMode=b.dataset.mode;game.dirtyShop=true;updateUI()});$('#exportBtn').onclick=exportSave;$('#importBtn').onclick=importSave;$('#resetBtn').onclick=reset;renderShop();renderUpgrades();renderAch();updateUI();setInterval(save,10000);setInterval(()=>{$('#newsText').textContent=NEWS[Math.floor(Math.random()*NEWS.length)]+' •'},15000);log('Partie chargée');requestAnimationFrame(loop)}
window.addEventListener('load',init);
